import type { FeedGroup } from '../app/types/feed'
// 友链检测 CLI 需要使用显式导入和相对路径
import { myFeed } from '../blog.config'
// eslint-disable-next-line unused-imports/no-unused-imports
import { getFavicon, getGithubAvatar, getGithubIcon, getOciqGroupAvatar, getOicqAvatar, OicqAvatarSize } from './utils/img'

export default [
	// #region 友链
	{
		name: '友链',
		desc: '相互关注，彼此照亮。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			myFeed,
			{
				author: '倪谅',
				sitenick: '主站',
				title: '倪哥买提大巴扎（主站）',
				desc: '烤肉 man 的日常',
				link: 'https://www.gnix807.cn',
				feed: 'https://www.gnix807.cn/rss.xml',
				icon: 'https://img.gnix807.cn/Logo_small.jpeg',
				avatar: 'https://img.gnix807.cn/Logo_small.jpeg',
				date: '2026-07-12',
				comment: '这是我的另一个站。',
			},
			{
				author: '林间拾语',
				desc: '技术与生活的温暖拾遗',
				link: 'https://www.xhhao.com',
				icon: 'https://www.xhhao.com/upload/logo.png',
				avatar: 'https://www.xhhao.com/upload/logo.png',
				date: '2026-07-12',
			},
			{
				author: 'KITA',
				desc: '归去来兮辞',
				link: 'https://blog.houxiongxiong.icu',
				icon: 'https://blog.houxiongxiong.icu/upload/favicon/favicon.png',
				avatar: 'https://blog.houxiongxiong.icu/upload/favicon/favicon.png',
				date: '2026-07-12',
			},
			{
				author: '5ee 博客',
				desc: '一个乐于分享技术的博客',
				link: 'https://www.5ee.net',
				icon: 'https://lsky.5ee.net/lsky/2024/12/10/675799c108db1.gif',
				avatar: 'https://lsky.5ee.net/lsky/2024/12/10/675799c108db1.gif',
				date: '2026-07-12',
			},
			{
				author: '楠笙',
				desc: '记录生活与技术，空谈误国，实干兴邦',
				link: 'https://blog.nanshengwx.cn',
				icon: 'https://blog.nanshengwx.cn/upload/logo.png',
				avatar: 'https://blog.nanshengwx.cn/upload/logo.png',
				date: '2026-07-12',
			},
			{
				author: 'HuTao',
				title: 'HuTao\'s Blog',
				desc: '分享生活每一个瞬间',
				link: 'https://blog.xn--cdwq63c.top/',
				icon: 'https://img.xn--cdwq63c.top/file/img/hutao192X192.png',
				avatar: 'https://img.xn--cdwq63c.top/file/img/hutao192X192.png',
				date: '2026-07-12',
			},
			{
				author: 'BarryZed',
				title: 'BarryZed 的个人博客',
				desc: '分享电子生活，尽己所能记录问题与解决方案',
				link: 'https://www.barryzed.top/',
				icon: 'https://raw.githubusercontent.com/Barrryy/NotionNext/refs/heads/main/favicon.ico',
				avatar: 'https://raw.githubusercontent.com/Barrryy/NotionNext/refs/heads/main/favicon.ico',
				date: '2026-07-12',
			},
			{
				author: 'solaireh3',
				title: '愛しの君とこの世のはたて',
				desc: 'solaireh3\'s Blog',
				link: 'https://ashlord.com',
				icon: 'https://ashlord.com/upload/IMG_0999.jpeg',
				avatar: 'https://ashlord.com/upload/IMG_0999.jpeg',
				date: '2026-07-12',
			},
			{
				author: '忘川河畔',
				desc: '木已成舟，渡我者何人？',
				link: 'https://been.ee',
				icon: 'https://been.ee/link/flower.jpg',
				avatar: 'https://been.ee/link/flower.jpg',
				date: '2026-07-12',
			},
			{
				author: 'jsishsjsj',
				title: 'jsishsjsj 的生活随笔 | WSNN',
				desc: 'WSNN',
				link: 'https://xiao.nanniang.de',
				icon: 'https://cdn.nodeimage.com/i/KQRBXuv26AANiJtGd6hyo4LDyw31tN9h.webp',
				avatar: 'https://cdn.nodeimage.com/i/KQRBXuv26AANiJtGd6hyo4LDyw31tN9h.webp',
				date: '2026-07-12',
			},
			{
				author: '522 小椿',
				title: '522 小椿的小站',
				desc: '一个爱好二次元的个人博客小站',
				link: 'https://blog.522.plus',
				icon: 'https://blog.522.plus/wp-content/uploads/2024/05/cropped-chungbin_avatar.jpg',
				avatar: 'https://blog.522.plus/wp-content/uploads/2024/05/cropped-chungbin_avatar.jpg',
				date: '2026-07-12',
			},
			{
				author: '薇尔薇',
				desc: 'We\'re not exactly in a position to be trusted with secrets, are we?',
				link: 'https://www.vio.vin',
				icon: 'https://www.vio.vin/favicon.ico',
				avatar: 'https://www.vio.vin/favicon.ico',
				date: '2026-07-12',
			},
			{
				author: 'SamHou',
				title: 'SamHou\'s Blog',
				desc: 'Sleep for a better life.',
				link: 'https://blog.samhou.moe/',
				icon: 'https://img.samhou.top/SamHou.png',
				avatar: 'https://img.samhou.top/SamHou.png',
				date: '2026-07-12',
			},
			{
				author: 'Mikuの鬆',
				sitenick: '极光星',
				title: 'Mikuの极光星',
				desc: '分享技术与生活',
				link: 'https://blog.sotkg.com/',
				feed: 'https://blog.sotkg.com/atom.xml',
				icon: 'https://cn.cravatar.com/avatar/1012bf78fb01d5b964c3a9a0f515911a.png',
				avatar: 'https://cn.cravatar.com/avatar/1012bf78fb01d5b964c3a9a0f515911a.png',
				date: '2026-07-12',
			},
			{
				author: 'Auriel',
				title: 'Auriel の主页',
				desc: '生活的最佳状态，是冷冷清清的风风火火。',
				link: 'https://www.auriel.top/',
				icon: 'https://www.auriel.top/favicon.ico',
				avatar: 'https://www.auriel.top/favicon.ico',
				date: '2026-07-12',
			},
			{
				author: 'VnYzm',
				title: 'VnYzm 的博客',
				desc: '分享技术心得和摸鱼感想',
				link: 'https://vnyzm.top',
				feed: 'https://vnyzm.top/extra/atom.xml',
				icon: 'https://vnyzm.top/img/favicon.ico',
				avatar: 'https://vnyzm.top/img/profile.jpg',
				date: '2026-07-12',
			},
			{
				author: 'butlanys',
				title: 'butlanys 的博客',
				desc: '愿此行，终抵群星。记录折腾、旅行与日常。',
				link: 'https://butlanys.de/',
				icon: 'https://butlanys.de/favicon.ico',
				avatar: 'https://butlanys.de/favicon.ico',
				date: '2026-07-12',
			},
			{
				author: '猫猫博客',
				desc: '动画 BDRIP/Remux 资源、Emby/PT/VPS 与服务器测评分享。',
				link: 'https://catcat.blog',
				icon: 'https://s3.catcat.blog/avatar.avif',
				avatar: 'https://s3.catcat.blog/avatar.avif',
				date: '2026-07-12',
			},
			{
				author: 'cosine',
				sitenick: '余弦',
				title: '余弦の博客',
				desc: 'FE / ACG / 手工 / 深色模式强迫症 / INFP / 兴趣广泛养两只猫的老宅女 / remote',
				link: 'https://blog.cosine.ren/',
				feed: 'https://blog.cosine.ren/rss.xml',
				icon: 'https://blog.cosine.ren/favicon.ico',
				avatar: 'https://blog.cosine.ren/img/avatar.webp',
				date: '2026-07-12',
			},
		],
	},
	// #endregion
] satisfies FeedGroup[]
